# Generated by Django 3.1.7 on 2021-03-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='plato',
        ),
        migrations.AddField(
            model_name='plato',
            name='ingredientes',
            field=models.ManyToManyField(to='menuapp.Ingrediente'),
        ),
    ]
